compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
networks:
  development:
    cmd_settings:
      unlock:
        - 0x5406a48f5de499c08bfb8939a3b9e66c1957d72b
